variables:
  REGISTRY_URL: registry-harbor.app.bangun-kreatif.com
  REGISTRY_IMAGE: $REGISTRY_URL/openbanking/ob-frontend
  VERSION_STAGING: $CI_COMMIT_REF_NAME-$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA
  VERSION_PRODUCTION: $CI_COMMIT_REF_NAME-$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA-production
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  STAGING_BASE_URL: https://cdi-backend.k3s.bangun-kreatif.com
  CLONE_BASE_URL: https://api.cdi-clone.app.bangun-kreatif.com
  STAGING_AUTH_SERVICE: /auth-service
  STAGING_GOOGLE_ANALYTICS: G-9DPHCQ3ZYP
  STAGING_SITEKEYCAPTCHA: 6LfNdRofAAAAANMG3hYfhnHvVJX_Ma2JhxC2afk6

stages:
  - build-staging
  - deploy-staging
  - build-production
  - deploy-production
  - build-clone

build-staging:
  stage: build-staging
  image: appuio/gitlab-runner-oc:3.11.0
  only:
    - devops-staging
  services:
    - docker:dind
  script:
    - docker login $REGISTRY_URL -u $BKA_REGISTRY_USER -p $BKA_REGISTRY_PASS
    - docker build -t $REGISTRY_IMAGE:$VERSION_STAGING .
    - docker push $REGISTRY_IMAGE:$VERSION_STAGING
    - docker rmi $REGISTRY_IMAGE:$VERSION_STAGING

deploy-staging:
  stage: deploy-staging
  image: dtzar/helm-kubectl
  only:
    - devops-staging
  script:
    - kubectl config set-cluster k8s --server="${BKA_CLUSTER_HOST}"
    - kubectl config set clusters.k8s.certificate-authority-data ${BKA_CLUSTER_CA}
    - kubectl config set-credentials gitlab --token="${BKA_CLUSTER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<VERSION>/${VERSION_STAGING}/g" k8s/staging/deployment.yaml
    - kubectl apply -f k8s/staging/deployment.yaml

build-production:
  stage: build-production
  image: appuio/gitlab-runner-oc:3.11.0
  only:
    - devops-production
  services:
    - docker:dind
  script:
    - docker login $REGISTRY_URL -u $BKA_REGISTRY_USER -p $BKA_REGISTRY_PASS
    - docker build -t $REGISTRY_IMAGE:$VERSION_PRODUCTION .
    - docker push $REGISTRY_IMAGE:$VERSION_PRODUCTION
    - docker rmi $REGISTRY_IMAGE:$VERSION_PRODUCTION

deploy-production:
  stage: deploy-production
  image: dtzar/helm-kubectl
  only:
    - devops-production
  script:
    - kubectl config set-cluster k8s --server="${BKA_CLUSTER_HOST}"
    - kubectl config set clusters.k8s.certificate-authority-data ${BKA_CLUSTER_CA}
    - kubectl config set-credentials gitlab --token="${BKA_CLUSTER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<VERSION>/${VERSION_PRODUCTION}/g" k8s/production/deployment.yaml
    - kubectl apply -f k8s/production/deployment.yaml

build-clone:
  stage: build-clone
  image: appuio/gitlab-runner-oc:3.11.0
  only:
    - devops-clone
  services:
    - docker:dind
  script:
    - docker login $REGISTRY_URL -u $BKA_REGISTRY_USER -p $BKA_REGISTRY_PASS
    - docker build -t $REGISTRY_IMAGE:$VERSION_PRODUCTION . --build-arg NEXT_PUBLIC_BASE_URL=$CLONE_BASE_URL --build-arg NEXT_PUBLIC_AUTH_SERVICE=$STAGING_AUTH_SERVICE --build-arg NEXT_PUBLIC_GOOGLE_ANALYTICS=$STAGING_GOOGLE_ANALYTICS --build-arg NEXT_PUBLIC_SITEKEYCAPTCHA=$STAGING_SITEKEYCAPTCHA
    - docker push $REGISTRY_IMAGE:$VERSION_PRODUCTION
    - docker rmi $REGISTRY_IMAGE:$VERSION_PRODUCTION
