export const styles = {
    input: {
        height: "50px",
        backgroundColor: "#fff",
        fontSize: "17px",
    },
    forgotPassword: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-end",
        marginBottom: "10px",
        marginTop: "-15px",
    },
    otpInput: {
        width: 60,
        height: 60,
        borderRadius: "10px",
        border: "1px solid #CBDFFF",
        backgroundColor: "#FFFFFF",
        color: "#145FD9",
        fontSize: "20px",
        fontWeight: "bold",
        textAlign: "center",
        padding: "10px",
        marginTop: "40px",
        marginBottom: "10px",
        marginLeft: "10px",
        marginRight: "10px",
    },
    otpInput6: {
        width: 40,
        height: 40,
        borderRadius: "10px",
        border: "1px solid #CBDFFF",
        backgroundColor: "#FFFFFF",
        color: "#145FD9",
        fontSize: "20px",
        fontWeight: "bold",
        textAlign: "center",
        padding: "10px",
        marginTop: "30px",
        marginBottom: "10px",
        marginLeft: "10px",
        marginRight: "10px",
    },
    button: {
        padding: "1.5rem 1rem",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        fontSize: "19px",
        letterSpacing: "1px",
    },
};
