export const styles = {
  body: {
    padding: 20,
    backgroundColor: "#F6F6F6",
    minHeight: "100vh",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  logoGopay: {
    marginLeft: "auto",
    marginRight: "auto",
    width: 150,
  },
  otpInput: {
    width: 60,
    height: 60,
    borderRadius: "10px",
    border: "1px solid #CBDFFF",
    backgroundColor: "#FFFFFF",
    color: "#145FD9",
    fontSize: "20px",
    fontWeight: "bold",
    textAlign: "center",
    padding: "10px",
    marginTop: "10px",
    marginBottom: "10px",
    marginLeft: "10px",
    marginRight: "10px",
  },
  button: {
    backgroundColor: "#B4BCC9",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "10px",
    padding: "10px",
    fontSize: "16px",
    marginTop: "10px",
    marginBottom: "10px",
    width: "100%",
  },
};
